dependencies:
  #- <organization/rep0>@<version>
  - smartcontractkit/chainlink-brownie-contracts@0.6.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.6.1'
dotenv: .env
networks:
  default: development
  mainnet-fork-dev:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    verify: False
  development:
    verify: False
wallets:
  from_key: ${PRIVATE_KEY}